server_cert: /Users/sashab1/work/optimus-deploy/out/127.0.0.1.crt
server_key: /Users/sashab1/work/optimus-deploy/out/127.0.0.1.key
ca_cert: /Users/sashab1/work/optimus-deploy/out/optimus.crt
listen_on: :50051
db_uri: postgres://localhost/optimus?sslmode=disable