client_cert: /Users/macbook/go/src/gitlab.com/lambda-hse/optimus/out/test-user.crt
client_key: /Users/macbook/go/src/gitlab.com/lambda-hse/optimus/out/test-user.key
ca_cert: /Users/macbook/go/src/gitlab.com/lambda-hse/optimus/out/disneyland.crt
connect_to: 127.0.0.1:50051
db_uri: postgres://localhost/disneyland?sslmode=disable